// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHVyIIJwgCc07p90vgJ8fOG8ZXPtGbBxY',
    appId: '1:786025265658:web:004a9a444508d00fbc0c43',
    messagingSenderId: '786025265658',
    projectId: 'pdp-bazar-home-29ffd',
    authDomain: 'pdp-bazar-home-29ffd.firebaseapp.com',
    storageBucket: 'pdp-bazar-home-29ffd.appspot.com',
    measurementId: 'G-9LZ0M0ZBF6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjP-bngNRG7EpuUJwuvrQSln4B1DXswFE',
    appId: '1:786025265658:android:17cd9e53913ff6aabc0c43',
    messagingSenderId: '786025265658',
    projectId: 'pdp-bazar-home-29ffd',
    storageBucket: 'pdp-bazar-home-29ffd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNw0LooscNyLtltJQOPwCE_Ink8eECW6Q',
    appId: '1:786025265658:ios:7c5c2ccb516ce44ebc0c43',
    messagingSenderId: '786025265658',
    projectId: 'pdp-bazar-home-29ffd',
    storageBucket: 'pdp-bazar-home-29ffd.appspot.com',
    iosClientId: '786025265658-2er46l8qlprbkqqh8ukmro96jtf671eb.apps.googleusercontent.com',
    iosBundleId: 'com.pdp.pdpBazarHome',
  );
}
